/**
* OOPSBannerApp UC3 – Banner Display Application
*
* This class demonstrates the creation of a visual banner displaying the word "OOPS"
* using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
* console using individual print statements for each line, creating a decorative
* text effect.
*
* The banner is generated by printing predefined string patterns line by line,
* where each line contributes to forming the letters O, O, P, and S in a stylized format.
* This extends a basic user story by adding visual presentation to a simple message output.
* We now use String join to print the OOPS Banner
* @author Developer
* @version 3
*/
 
public class PrintOOPS {
    public static void main(String[] args){
        System.out.println(String.join(" "," *******  "+" *******  "+" *******  "+" *******  "));
        System.out.println(String.join(" ","*       * "+"*       * "+"*       * "+" *        "));
        System.out.println(String.join(" ","*       * "+"*       * "+"*       * "+" *        "));
        System.out.println(String.join(" ","*       * "+"*       * "+" *******  "+" *******  "));
		System.out.println(String.join(" ","*       * "+"*       * "+"*        "+"        *  "));
        System.out.println(String.join(" ","*       * "+"*       * "+"*        "+"        *  "));
        System.out.println(String.join(" "," *******  "+" *******  "+"*        "+"  *******  "));

    }

}


