/**

* OOPSBannerApp UC4 – Banner Display Application
*
* This class demonstrates the creation of a visual banner displaying the word "OOPS"
* using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
* console using individual print statements for each line, creating a decorative
* text effect.
*
* The banner is generated by printing predefined string patterns line by line,
* where each line contributes to forming the letters O, O, P, and S in a stylized format.
* This extends a basic user story by adding visual presentation to	 a simple message output.
* We now use String join to print the OOPS Banner
* after using string join, to reduce friction while printing out, we now use as array and for loop
* @author Developer
* @version 4

*/
 
class PrintOOPS{

	public static void main(String[] args){
		String[] str = new String[9];
		str[0] = String.join(" ", "    ***    " , "     ***    " , " *******  " , "   *****  ");
		str[1] = String.join(" ", " **     ** " , "  **     ** " , " **    ** " , "  **      ");
		str[2] = String.join(" ", "**       **" , " **       **" , " **     **" , " **       ");
		str[3] = String.join(" ", "**       **" , " **       **" , " **    ** " , "  **      ");	
		str[4] = String.join(" ", "**       **" , " **       **" , " ****     " , "   ***    ");
		str[5] = String.join(" ", "**       **" , " **       **" , " **       " , "      ** ");
		str[6] = String.join(" ", "**       **" , " **       **" , " **       " , "       **");
		str[7] = String.join(" ", " **     ** " , "  **     ** " , " **       " , "      ** ");
		str[8] = String.join(" ", "    ***    " , "     ***    " , " **       " , "  ******  ");
		for(String itr: str){
				System.out.println(itr);
		}

	}

}