/**
* OOPSBannerApp UC8 – Banner Display Application
*
* This class demonstrates the creation of a visual banner displaying the word "OOPS"
* using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
* console using individual print statements for each line, creating a decorative
* text effect.
*
* The banner is generated by printing predefined string patterns line by line,
* where each line contributes to forming the letters O, O, P, and S in a stylized format.
* This extends a basic user story by adding visual presentation to a simple message output.
* This program uses String Join, for each loop to print, along with initiating String array without new String [] and using a new class to call function to return the string and using inner class.
* @author Developer
* @version 8
*/

import java.util.*;
public class PrintOOPS{

	public static void main(String[] args){
		HashMap<Character, String[]> charMap = createCharacterMap();
		String message = "OOPS";
		displayBanner(message, charMap);

	}
	
	public static HashMap<Character, String[]> createCharacterMap(){
		HashMap<Character, String[]> charMap = new HashMap<>();
		charMap.put('O', new String[]{" *****  ", "*     * ", "*     * ", "*     * ", "*     * ", " *****  "});
		charMap.put('P', new String[]{"******* ", "*     * ", "*     * ", "*******", "*       ", "*      "});
		charMap.put('S', new String[]{" *****  ", " *     ", " *     ", "  ***** ", "     * ", "  ***** "});
		return charMap;
	
	}
	

	
	public static void displayBanner(String message, HashMap<Character, String[]> charMap){
		for(int i=0; i<6; i++){
			for(char c: message.toCharArray()){
				System.out.print(charMap.get(c)[i]+" ");
			}
			System.out.println();
		}
		
	}
	

}

